export const officers = [
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: false,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
  {
    email: "hshfhk@jhkjf.com",
    password: "123456",
    firstName: "Андрей",
    lastName: "Мощенко",
    clientId: "2412412sdf",
    approved: true,
  },
];
